version: '3.4'
services:
    node01:
        image: daocloud.io/buxiaomo/zookeeper:3.4.10
        networks:
            zookeeper:
        environment:
            ZOOKEEPER_CONFIG: |
                id=1
                zookeeper.cluster=172.16.0.6:2888:3888,172.16.0.11:2888:3888,172.16.0.2:2888:3888
        # configs:
        #     - source: zk01
        #       target: /usr/local/zookeeper-3.4.10/conf/zoo.cfg
        #       mode: 0644
        volumes:
            - /var/lib/zookeeper:/var/lib/zookeeper:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                order: stop-first
            # resources:
            #     limits:
            #         cpus: '2'
            #         memory: 1G
            #     reservations:
            #         cpus: '1'
            #         memory: 500M
            placement:
                constraints:
                    - node.labels.zookeeper.node01 == true
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

    node02:
        image: daocloud.io/buxiaomo/zookeeper:3.4.10
        networks:
            zookeeper:
        environment:
            ZOOKEEPER_CONFIG: |
                id=2
                zookeeper.cluster=172.16.0.6:2888:3888,172.16.0.11:2888:3888,172.16.0.2:2888:3888
        # configs:
        #     - source: zk02
        #       target: /usr/local/zookeeper-3.4.10/conf/zoo.cfg
        #       mode: 0644
        volumes:
            - /var/lib/zookeeper:/var/lib/zookeeper:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                order: stop-first
            # resources:
            #     limits:
            #         cpus: '2'
            #         memory: 1G
            #     reservations:
            #         cpus: '1'
            #         memory: 500M
            placement:
                constraints:
                    - node.labels.zookeeper.node02 == true
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

    node03:
        image: daocloud.io/buxiaomo/zookeeper:3.4.10
        networks:
            zookeeper:
        environment:
            ZOOKEEPER_CONFIG: |
                id=3
                zzookeeper.cluster=172.16.0.6:2888:3888,172.16.0.11:2888:3888,172.16.0.2:2888:3888
        # configs:
        #     - source: zk03
        #       target: /usr/local/zookeeper-3.4.10/conf/zoo.cfg
        #       mode: 0644
        volumes:
            - /var/lib/zookeeper:/var/lib/zookeeper:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                order: stop-first
            # resources:
            #     limits:
            #         cpus: '2'
            #         memory: 1G
            #     reservations:
            #         cpus: '1'
            #         memory: 500M
            placement:
                constraints:
                    - node.labels.zookeeper.node03 == true
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
# configs:
#     zk01:
#         file: ./zk01.cfg
#     zk02:
#         file: ./zk02.cfg
#     zk03:
#         file: ./zk03.cfg

networks:
    zookeeper:
        external:
            name: "host"